export const styles = StyleSheet.create({
    wrapper: {
      alignItems: "center",
      justifyContent: "center",
      flex: 1,
      margin: 0,
      padding: 0,
      marginTop: Platform.OS === "android" ? StatusBar.currentHeight + 10 : 0,
    },
    container: {
      width: containerWidth,
      height: containerWidth,
      margin: 10,
    },
    playContainer: {
      width: "100%",
      height: "40%",
      flexDirection: "row",
    },
    homeContainer: {
      width: "100%",
      height: "20%",
      flexDirection: "row",
    },
    startArea: {
      width: "40%",
      height: "100%",
      alignItems: "center",
      justifyContent: "center",
      flex: 1,
    },
    verticalPath: {
      width: "20%",
      height: "100%",
      flexDirection: "row",
      flexWrap: "wrap",
    },
    horizontalPath: {
      width: "40%",
      height: "100%",
      flexDirection: "row",
      flexWrap: "wrap",
    },
    homePath: {
      width: "20%",
      height: "100%",
    },
    green: {
      backgroundColor: "#84c21f",
    },
    red: {
      backgroundColor: "#dc2418",
    },
    blue: {
      backgroundColor: "#0092dc",
    },
    yellow: {
      backgroundColor: "#f6c700",
    },
    white: {
      backgroundColor: "#fff",
    },
    subStartArea: {
      width: "70%",
      height: "70%",
      flexDirection: "row",
      flexWrap: "wrap",
    },
    subStartArea_View: {
      width: "35%",
      height: "35%",
      margin: "7.5%",
      shadowColor: "rgba(0, 0, 0, 0.16)",
      shadowOffset: {
        width: 0,
        height: 3,
      },
      shadowRadius: 6,
      shadowOpacity: 1,
      elevation: 3,
      backgroundColor: "white",
      transition: "all 0.3s",
      transform: [{ scaleX: 1.05 }],
    },
    subVerticalPath: {
      width: "33.33%",
      height: "16.667%",
      borderWidth: 1,
      borderColor: "#000",
    },
    subHorizontalPath: {
      height: "33.33%",
      width: "16.66%",
      borderWidth: 1,
      borderColor: "#000",
    },
    centered: {
      justifyContent: "center",
      alignItems: "center",
    },
    triangleContainer: {
      width: "100%",
      height: "100%",
      position: "relative",
      justifyContent: "center",
      alignItems: "center",
    },
    triangleRight: {
      width: 0,
      height: 0,
      backgroundColor: "transparent",
      borderStyle: "solid",
      borderLeftWidth: bwidth,
      borderTopWidth: bwidth,
      borderBottomWidth: bwidth,
      borderLeftColor: "#84c21f",
      borderTopColor: "transparent",
      borderBottomColor: "transparent",
      position: "absolute",
      left: 0,
    },
    triangleUp: {
      width: 0,
      height: 0,
      backgroundColor: "transparent",
      borderStyle: "solid",
      borderLeftWidth: bwidth,
      borderRightWidth: bwidth,
      borderBottomWidth: bwidth,
      borderLeftColor: "transparent",
      borderRightColor: "transparent",
      borderBottomColor: "#dc2418",
      position: "absolute",
      bottom: 0,
    },
    triangleLeft: {
      width: 0,
      height: 0,
      backgroundColor: "transparent",
      borderStyle: "solid",
      borderTopWidth: bwidth,
      borderRightWidth: bwidth,
      borderBottomWidth: bwidth,
      borderTopColor: "transparent",
      borderRightColor: "#0092dc",
      borderBottomColor: "transparent",
      position: "absolute",
      right: 0,
    },
    triangleDown: {
      width: 0,
      height: 0,
      backgroundColor: "transparent",
      borderStyle: "solid",
      borderTopWidth: bwidth,
      borderRightWidth: bwidth,
      borderLeftWidth: bwidth,
      borderTopColor: "#f6c700",
      borderRightColor: "transparent",
      borderLeftColor: "transparent",
      position: "absolute",
      top: 0,
    },
    circle: {
      height: "60%",
      width: "60%",
      position: "absolute",
      backgroundColor: "#fff",
      borderRadius: 50,
      justifyContent: "center",
      alignItems: "center",
    },
    text: {
      color: "#000",
    },
    textStyle: {
      fontSize: minScreenDimension * 0.03,
      fontWeight: "bold",
    },
  });